# Railway Nixpacks Configuration for Client Service (Monorepo)

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd ../.. && npm install && cd apps/client']

[phases.build]
cmds = ['cd ../.. && npx turbo run build --filter=@rentalshop/client && cd apps/client']

[start]
cmd = 'node .next/standalone/apps/client/server.js'

