# Railway Nixpacks Configuration for Admin Service (Monorepo)

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['cd ../.. && npm install && cd apps/admin']

[phases.build]
cmds = ['cd ../.. && npx turbo run build --filter=@rentalshop/admin && cd apps/admin']

[start]
cmd = 'node .next/standalone/apps/admin/server.js'

