# Nixpacks configuration for Railway deployment (Admin App)

[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  # Build admin app from root to ensure workspace packages are available
  "cd apps/admin && yarn build"
]

[start]
cmd = "cd apps/admin && yarn start:standalone"

[variables]
NODE_ENV = "production"

