# Railway Nixpacks Configuration for Admin Service (Monorepo)

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['echo "Skipping auto-install phase"']

[phases.build]
cmds = [
  'cd ../..',
  'npm install',
  'npx turbo run build --filter=@rentalshop/admin',
  'cd apps/admin'
]

[start]
cmd = 'node .next/standalone/apps/admin/server.js'

