export const LOYALTY_TRANSACTION_TYPES = {
  EARN: 'earn',
  REDEEM: 'redeem',
  ADJUST: 'adjust',
  REFUND: 'refund',
  EXPIRE: 'expire',
  TIER_UPGRADE: 'tier_upgrade',
} as const;

export type LoyaltyTransactionType =
  (typeof LOYALTY_TRANSACTION_TYPES)[keyof typeof LOYALTY_TRANSACTION_TYPES];

export const LOYALTY_REDEEM_REASONS = {
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  BELOW_MINIMUM: 'BELOW_MINIMUM',
  EXCEEDS_MAX_PERCENT: 'EXCEEDS_MAX_PERCENT',
  EXCEEDS_REMAINING_AMOUNT: 'EXCEEDS_REMAINING_AMOUNT',
  REDEEM_DISABLED_FOR_ORDER_TYPE: 'REDEEM_DISABLED_FOR_ORDER_TYPE',
  PROGRAM_INACTIVE: 'PROGRAM_INACTIVE',
  NO_LOYALTY_RECORD: 'NO_LOYALTY_RECORD',
} as const;

export type LoyaltyRedeemReason =
  (typeof LOYALTY_REDEEM_REASONS)[keyof typeof LOYALTY_REDEEM_REASONS];
