// ============================================================================
// PLAN TYPES
// ============================================================================

export interface Plan {
  id: string;                    // Database CUID
  publicId: number;              // Public ID for external use
  name: string;                  // Plan name (e.g., "Basic", "Professional", "Enterprise")
  description: string;           // Plan description
  basePrice: number;             // Base price for monthly calculations
  currency: string;              // Currency code (USD, VND)
  trialDays: number;             // Number of trial days
  limits: {                      // Plan limits
    outlets: number;             // Maximum number of outlets allowed
    users: number;               // Maximum number of users allowed
    products: number;            // Maximum number of products allowed
    customers: number;           // Maximum number of customers allowed
  };
  features: string[];            // Array of feature strings
  isActive: boolean;             // Whether the plan is active
  isPopular: boolean;            // Whether to highlight this plan
  sortOrder: number;             // Display order
  createdAt: Date;
  updatedAt: Date;
  
  // Modern pricing structure
  pricing: {
    monthly: {
      price: number;
      discount: number;
      savings: number;
      interval: 'month';
      intervalCount: 1;
    };
    quarterly: {
      price: number;
      discount: number;
      savings: number;
      interval: 'quarter';
      intervalCount: 3;
    };
    yearly: {
      price: number;
      discount: number;
      savings: number;
      interval: 'year';
      intervalCount: 1;
    };
  };
}

export type BillingCycle = 'monthly' | 'quarterly' | 'semi_annual' | 'annual';

export interface BillingCycleOption {
  value: BillingCycle;
  label: string;
  months: number;
  description: string;
}

export interface PlanCreateInput {
  name: string;
  description: string;
  basePrice: number;             // Base price for monthly calculations
  currency?: string;
  trialDays: number;
  limits: {
    outlets: number;
    users: number;
    products: number;
    customers: number;
  };
  features: string[];
  isActive?: boolean;
  isPopular?: boolean;
  sortOrder?: number;
  // publicId is auto-generated by database, not required in input
}

export interface PlanUpdateInput {
  name?: string;
  description?: string;
  basePrice?: number;            // Base price for monthly calculations
  currency?: string;
  trialDays?: number;
  limits?: {
    outlets?: number;
    users?: number;
    products?: number;
    customers?: number;
  };
  features?: string[];
  isActive?: boolean;
  isPopular?: boolean;
  sortOrder?: number;
}

export interface PlanFilters {
  search?: string;
  isActive?: boolean;
  isPopular?: boolean;
  limit?: number;
  offset?: number;
  sortBy?: 'name' | 'price' | 'basePrice' | 'createdAt' | 'sortOrder';  // ✅ Updated: Support both price and basePrice
  sortOrder?: 'asc' | 'desc';
}

export interface PlanFeature {
  id: number;
  name: string;
  description: string;
  icon: string;
  isIncluded: boolean;
}

export interface PlanComparison {
  basic: Plan;
  professional: Plan;
  enterprise: Plan;
}

// Plan variants removed - Using modern subscription system with dynamic pricing
