# Railway Nixpacks Configuration for API Service (Monorepo)

[phases.setup]
nixPkgs = ['nodejs_18', 'openssl']

[phases.install]
# Install from monorepo root to handle workspace dependencies
cmds = ['cd ../.. && npm install && cd apps/api']

[phases.build]
# Build from root with turbo
cmds = ['cd ../.. && npx prisma generate --schema=./prisma/schema.prisma && npx turbo run build --filter=@rentalshop/api && cd apps/api']

[start]
cmd = 'node .next/standalone/apps/api/server.js'

