# Nixpacks configuration for Railway deployment
# This ensures Prisma generates correctly in monorepo setup

[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
cmds = [
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = [
  # Generate Prisma Client in root node_modules
  "cd ../.. && npx prisma generate --schema=./prisma/schema.prisma",
  # Build the API app
  "cd apps/api && yarn build"
]

[start]
cmd = "cd apps/api && yarn start:standalone"

[variables]
NODE_ENV = "production"

